### ISSUE TITLE
Error when trying to rename contract

### ISSUE THREAD

**Issue by ZDigitalDesigns** [hashlips-lab/nft-erc721-collection#121]
yarn run v1.22.15
warning package.json: No license field
$ hardhat rename-contract TestSmokey
An unexpected error occurred:

SyntaxError: /Users/zywenvergara/Desktop/nft-erc721-collection-2.0.0/smart-contract/config/whitelist.json: Unexpected token ] in JSON at position 50
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1128:22)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/zywenvergara/Desktop/nft-erc721-collection-2.0.0/smart-contract/config/CollectionConfig.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module.m._compile (/Users/zywenvergara/Desktop/nft-erc721-collection-2.0.0/smart-contract/node_modules/ts-node/src/index.ts:1475:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by liarco** [comment]
Hi @ZDigitalDesigns,
The error should be self-explanatory:

```
SyntaxError: /Users/zywenvergara/Desktop/nft-erc721-collection-2.0.0/smart-contract/config/whitelist.json: Unexpected token ] in JSON at position 50
```

Your `whitelist.json` file is not valid.
Maybe you left a trailing comma? Visual Studio Code should tell you what's wrong if you open the file.
