### ISSUE TITLE
Unpredictable Gas Limit

### ISSUE THREAD

**Issue by coffeeclubnfts** [hashlips-lab/nft-erc721-collection#135]
When trying to close my whitelist sale, I keep getting this error:

`$ hardhat run scripts/3_whitelist_close.ts --network truffle
No need to generate any newer typings.
Disabling whitelist sale...
Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":-32603,"_isProviderError":true,"data":{"originalError":{"code":3,"data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000204f776e61626c653a2063616c6c6572206973206e6f7420746865206f776e6572","message":"execution reverted: Ownable: caller is not the owner"}}}, method="estimateGas", transaction={"from":"0xFdbFc57c3e5Ec7cFC4fc437b2601391B82fBA541","to":"0x9c22b85F9B060067ea5aCE3Ed91C951a4100431A","data":"0xb767a0980000000000000000000000000000000000000000000000000000000000000000","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.3)
    at Logger.makeError (/Users/timemachine/Desktop/coffeetest/smart-contract/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/Users/timemachine/Desktop/coffeetest/smart-contract/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at checkError (/Users/timemachine/Desktop/coffeetest/smart-contract/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:80:16)
    at EthersProviderWrapper.<anonymous> (/Users/timemachine/Desktop/coffeetest/smart-contract/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:562:20)
    at step (/Users/timemachine/Desktop/coffeetest/smart-contract/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/Users/timemachine/Desktop/coffeetest/smart-contract/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/Users/timemachine/Desktop/coffeetest/smart-contract/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: ProviderError: execution reverted: Ownable: caller is not the owner
      at HttpProvider.request (/Users/timemachine/Desktop/coffeetest/smart-contract/node_modules/hardhat/src/internal/core/providers/http.ts:74:19)
      at GanacheGasMultiplierProvider.request (/Users/timemachine/Desktop/coffeetest/smart-contract/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:312:34)
      at processTicksAndRejections (node:internal/process/task_queues:96:5),
  method: 'estimateGas',
  transaction: {
    from: '0xFdbFc57c3e5Ec7cFC4fc437b2601391B82fBA541',
    to: '0x9c22b85F9B060067ea5aCE3Ed91C951a4100431A',
    data: '0xb767a0980000000000000000000000000000000000000000000000000000000000000000',
    accessList: null
  }
}
error Command failed with exit code 1.`

**Comment by liarco** [comment]
Hi @coffeeclubnfts please read the errors carefully because most of the times you will see that they already contain an explanation of what's happening: `ProviderError: execution reverted: Ownable: caller is not the owner`

You should run the management functions using the same address that you used when deploying the contract. 😉
