### ISSUE TITLE
Couldn't find the binary git

### ISSUE THREAD

**Issue by ericrainford** [hashlips-lab/nft-erc721-collection#307]
### General information
| Description | Value |
| --- | --- |
| nft-erc721-collection v2.0.0|  |
| Windows 10 |
| NodeJS version | v14.8.2 |
| NPM version | 6.14.15 |
| Yarn version | 1.22.15 |
| Truffle version | TypeError: Cannot read property 'name' of null
    at prepareOptions (C:\Users\ericr\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\command-utils.js:86:39)
    at Object.586806 (C:\Users\ericr\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\cli.js:65:1)
    at __webpack_require__ (C:\Users\ericr\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\bootstrap:19:1)
    at C:\Users\ericr\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\bootstrap:37:1
    at Function.__webpack_require__.O (C:\Users\ericr\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\runtime\chunk loaded:23:1)
    at __webpack_require__.x (C:\Users\ericr\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\bootstrap:38:1)
    at Function.__webpack_require__.x (C:\Users\ericr\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\runtime\startup chunk dependencies:35:1)
    at C:\Users\ericr\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\startup:3:1
    at Object.<anonymous> (C:\Users\ericr\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:627:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 | I get this when I run truffle --version not sure if this could be part of my issue

Couldn't find the binary git
I am following the How to create an NFT collection - Masterclass and have been successful up until the part where you have to run yarn in the root of the smart-contract, when I run yarn this I what I get
warning package.json: No license field
warning @hashlips-lab/nft-erc721-collection-smart-contract@1.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find the binary git

Any help would be greatly appreciated, unfortunately I do not know a lot about coding and just want to launch my nft collection, I've followed every step in Hashlips video word for word step by step I dont understand why I'm having this issue

**Comment by ericrainford** [comment]
figured it out!
