### ISSUE TITLE
Error while deploying to goerli with truffle 

### ISSUE THREAD

**Issue by rrigoni** [hashlips-lab/nft-erc721-collection#412]
The verify is not working. It seems to be an error in the nomiclabs plugin https://github.com/NomicFoundation/hardhat/issues/2247 

I updated all the dependencies, truffle, npm node and all the nomiclabs plugins. 

Any idea?

`Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify

NomicLabsHardhatPluginError: The contract verification failed.
Reason: Fail - Unable to verify
    at SimpleTaskDefinition.verifySubtask [as action] (/Users/ronaldo/projects/ndj/genesis-note/genesis-note-nft-contracts/smart-contract/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:350:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Environment._runTaskDefinition (/Users/ronaldo/projects/ndj/genesis-note/genesis-note-nft-contracts/smart-contract/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/Users/ronaldo/projects/ndj/genesis-note/genesis-note-nft-contracts/smart-contract/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at async Environment._runTaskDefinition (/Users/ronaldo/projects/ndj/genesis-note/genesis-note-nft-contracts/smart-contract/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/Users/ronaldo/projects/ndj/genesis-note/genesis-note-nft-contracts/smart-contract/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at async main (/Users/ronaldo/projects/ndj/genesis-note/genesis-note-nft-contracts/smart-contract/node_modules/hardhat/src/internal/cli/cli.ts:272:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Here is how to get the version numbers requested below:
* project version: is the one you downloaded or cloned from the repo
* operating system and version: https://www.google.com/search?q=how+to+know+know+operating+system+version
* NodeJS version: `node --version`
* NPM version: `npm --version`
* Yarn version: `yarn --version`
* Truffle version: `truffle --version`
-->

### General information
| Description | Value |
| --- | --- |
| Project version | X.Y.Z |
| Operating system and version | ??? |
| NodeJS version | X.Y.Z |
| NPM version | X.Y.Z |
| Yarn version | X.Y.Z |
| Truffle version | X.Y.Z |

### How to Reproduce
Steps to reproduce the behavior (please provide a reproducer project for complex bugs):

**Comment by rrigoni** [comment]
Ahh, and yes, I'm using the `ethereumTestnet` pointing to goerli. 
In this error I was using truffle dashboard

**Comment by 0xV4L3NT1N3** [comment]
gm @rrigoni, chiming in from Etherscan. We did have our Goerli node go down around this time causing contract verifications to remain as pending or failing. 

Do try this again and if it works for you, otherwise we'll need to look into other possibilities!

**Comment by liarco** [comment]
Thank you @0xV4L3NT1N3, for taking time to reply here. I really appreciate the helpful information.

**Comment by rrigoni** [comment]
This was an issue with Goerli being unstable.

**Comment by liarco** [comment]
Thank you @rrigoni for taking time to update on this. Glad to hear it was finally solved.
