### ISSUE TITLE
ProviderError: HttpProviderError

### ISSUE THREAD

**Issue by Sagezez** [hashlips-lab/nft-erc721-collection#453]
I'm trying to deploy a contract to Mumbai. This has been happening for nearly a week now and I have not been able to deploy. I have searched the error and it has been suggested to set the gas manually as opposed to automatically. Unfortunately, I am unsure where to add in the info.

Deploying contract...
ProviderError: HttpProviderError
at HttpProvider.request (C:\Users\lhopl\Desktop\TEST\nft-erc721-collection-2.4.5\smart-contract\node_modules\hardhat\src\internal\core\providers\http.ts:78:19)
at AutomaticSenderProvider.request (C:\Users\lhopl\Desktop\TEST\nft-erc721-collection-2.4.5\smart-contract\node_modules\hardhat\src\internal\core\providers\accounts.ts:344:34)
at AutomaticGasProvider.request (C:\Users\lhopl\Desktop\TEST\nft-erc721-collection-2.4.5\smart-contract\node_modules\hardhat\src\internal\core\providers\gas-providers.ts:135:34)
at AutomaticGasPriceProvider.request (C:\Users\lhopl\Desktop\TEST\nft-erc721-collection-2.4.5\smart-contract\node_modules\hardhat\src\internal\core\providers\gas-providers.ts:182:36)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async EthersProviderWrapper.send (C:\Users\lhopl\Desktop\TEST\nft-erc721-collection-2.4.5\smart-contract\node_modules@nomiclabs\hardhat-ethers\src\internal\ethers-provider-wrapper.ts:13:20)
error Command failed with exit code 1.

**Comment by SuzieBlue89** [comment]
Hey Dude, exact same Problem here with my project. Since i don´t find any solution, i was wondering if you find a way to fix?

**Comment by SuzieBlue89** [comment]
Looks like it is basicly the same problem. Would be very very happy.

ProviderError: HttpProviderError
    at HttpProvider.request (/Users/suzieblue/Desktop/nft-erc721-collection-2.4.5/smart-contract/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
    at AutomaticSenderProvider.request (/Users/suzieblue/Desktop/nft-erc721-collection-2.4.5/smart-contract/node_modules/hardhat/src/internal/core/providers/accounts.ts:344:34)
    at AutomaticGasProvider.request (/Users/suzieblue/Desktop/nft-erc721-collection-2.4.5/smart-contract/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:135:34)
    at AutomaticGasPriceProvider.request (/Users/suzieblue/Desktop/nft-erc721-collection-2.4.5/smart-contract/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:182:36)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async EthersProviderWrapper.send (/Users/suzieblue/Desktop/nft-erc721-collection-2.4.5/smart-contract/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

**Comment by liarco** [comment]
I'm sorry for the late reply, I never experienced anything like this before and I couldn't replicate this until the last couple of days when working on Mumbai (Polygon's testnet).
In my case I had to change the RPC endpoint as it was not working properly (you can change it from MetaMask if you are using Truffle). I used a private endpoint from [Alchemy](https://alchemy.com) and it worked fine.

I hope this helps.

**Comment by pentcle** [comment]
i had the same issue and tried out a few RPCs from chainlist (which i added to mm goerli rpc settings) to get it working

https://chainlist.org/chain/5
