### ISSUE TITLE
error in minting-dapp webpack

### ISSUE THREAD

**Issue by Amine3004** [hashlips-lab/nft-erc721-collection#71]
when i run yarn dev-server 
  `[webpack-cli] TypeError: compiler.plugin is not a function
    at ProvidePlugin.apply (C:\Users\amino\nft-erc721-collection-1.0.0\minting-dapp\node_modules\webpack\lib\ProvidePlugin.js:19:12)
    at createCompiler (C:\Users\amino\nft-erc721-collection-1.0.0\minting-dapp\node_modules\@symfony\webpack-encore\node_modules\webpack\lib\webpack.js:73:12)
    at create (C:\Users\amino\nft-erc721-collection-1.0.0\minting-dapp\node_modules\@symfony\webpack-encore\node_modules\webpack\lib\webpack.js:134:16)
    at webpack (C:\Users\amino\nft-erc721-collection-1.0.0\minting-dapp\node_modules\@symfony\webpack-encore\node_modules\webpack\lib\webpack.js:158:32)
    at WebpackCLI.f [as webpack] (C:\Users\amino\nft-erc721-collection-1.0.0\minting-dapp\node_modules\@symfony\webpack-encore\node_modules\webpack\lib\index.js:63:16)
    at WebpackCLI.createCompiler (C:\Users\amino\nft-erc721-collection-1.0.0\minting-dapp\node_modules\@symfony\webpack-encore\node_modules\webpack-cli\lib\webpack-cli.js:2193:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (C:\Users\amino\nft-erc721-collection-1.0.0\minting-dapp\node_modules\@symfony\webpack-encore\node_modules\@webpack-cli\serve\lib\index.js:106:30)
    at async Promise.all (index 1)
    at async Command.<anonymous> (C:\Users\amino\nft-erc721-collection-1.0.0\minting-dapp\node_modules\@symfony\webpack-encore\node_modules\webpack-cli\lib\webpack-cli.js:1674:7)`

**Comment by liarco** [comment]
Hi @Amine3004, please provide all the steps you run on the terminal. This error alone is not enough in order to understand what you might be missing.

**Comment by Aminooow** [comment]
1- Yarn
2- Yarn dev-server 
3- I got this error

**Comment by Aminooow** [comment]
I was following the hashlips video

**Comment by Aminooow** [comment]
???

**Comment by liarco** [comment]
> ???

@Aminooow (or @Amine3004, that's not clear), this is not a personal help-desk. Giving incomplete information or pinging like that is disrespectful and I won't warn you twice. Be patient and wait.

> I was following the hashlips video

The steps [you reported here](https://github.com/hashlips-lab/nft-erc721-collection/issues/71#issuecomment-1060012990) are incomplete, so I think you are skipping something before that. If you don't have experience with the tools used in the video you should stick to what's shown there.

Another possible issue might be the required tools (NodeJs, Yarn, etc.) not being installed correctly. In that case you should make sure they are running correctly, but unfortunately I can't support you with that.

**Comment by Aminooow** [comment]
I own Node and yarn

**Comment by Aminooow** [comment]
I have all the requirements The problem with webpack

**Comment by Aminooow** [comment]
Please help me
