### ISSUE TITLE
Error when running "yarn dev-server"

### ISSUE THREAD

**Issue by eaugustine30** [hashlips-lab/nft-erc721-collection#9]
Hello, I get this error every time I run "yarn dev-server".  I updated html-webpack-plugin in hopes that would help.  Still no luck.  Can anyone help me with this?

Terminal Message:

C:\...\minting-dapp\node_modules\webpack\lib\NormalModule.js:207
                        throw new TypeError(
                        ^

TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (C:\...\minting-dapp\node_modules\webpack\lib\NormalModule.js:207:10)
    at C:\...\minting-dapp\node_modules\@symfony\webpack-encore\lib\webpack-manifest-plugin\index.js:56:24
    at _next33 (eval at create (C:\...\minting-dapp\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:50:1)
    at _next11 (eval at create (C:\...\minting-dapp\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (C:\...\minting-dapp\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:123:1)
    at Hook.CALL_DELEGATE [as _call] (C:\...\minting-dapp\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (C:\...\minting-dapp\node_modules\webpack\lib\Compiler.js:1055:26)
    at C:\...\minting-dapp\node_modules\webpack\lib\Compiler.js:1099:29
    at Hook.eval [as callAsync] (eval at create (C:\...\minting-dapp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\...\minting-dapp\node_modules\tapable\lib\Hook.js:18:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by liarco** [comment]
Hi @eaugustine30, unfortunately this error doesn't seem related to our app. Many people reported the same issue for different projects (even pretty old ones).

Are you using yarn for other projects? I found some people saying that this has to do with multiple webpack versions being installed at the same time, you may have a webpack version installed as a global dependency... is this your case?

**Comment by liarco** [comment]
Closing for inactivity, feel free to reopen this if you can provide further information. Thank you.
